;---ioncube_loader---
zend_extension=/opt/alt/php70/usr/lib64/php/modules/ioncube_loader.so

;---dom---
extension=dom.so

;---fileinfo---
extension=fileinfo.so

;---gd---
extension=gd.so

;---imap---
extension=imap.so

;---json---
extension=json.so

;---mbstring---
extension=mbstring.so

;---mysqli---
extension=mysqli.so

;---pdo---
extension=pdo.so

;---pdo_mysql---
extension=pdo_mysql.so

;---pdo_sqlite---
extension=pdo_sqlite.so

;---phar---
extension=phar.so

;---posix---
extension=posix.so

;---sockets---
extension=sockets.so

;---sysvmsg---
extension=sysvmsg.so

;---sysvsem---
extension=sysvsem.so

;---sysvshm---
extension=sysvshm.so

;---wddx---
extension=wddx.so

;---xmlreader---
extension=xmlreader.so

;---xmlwriter---
extension=xmlwriter.so

;---xsl---
extension=xsl.so

;---zip---
extension=zip.so

