;---ioncube_loader---
zend_extension=/opt/alt/php83/usr/lib64/php/modules/ioncube_loader.so


;---bcmath---
extension=bcmath.so


;---dom---
extension=dom.so


;---fileinfo---
extension=fileinfo.so


;---gd---
extension=gd.so


;---imagick---
extension=imagick.so


;---intl---
extension=intl.so


;---mbstring---
extension=mbstring.so


;---mysqlnd---
extension=mysqlnd.so


;---mysqli---
extension=mysqli.so


;---pdo---
extension=pdo.so


;---nd_pdo_mysql---
extension=nd_pdo_mysql.so


;---pdo_sqlite---
extension=pdo_sqlite.so


;---phar---
extension=phar.so


;---soap---
extension=soap.so


;---sockets---
extension=sockets.so


;---xmlreader---
extension=xmlreader.so


;---xmlwriter---
extension=xmlwriter.so


;---xsl---
extension=xsl.so


;---zip---
extension=zip.so


;>=== Start of PHP Selector Custom Options ===
memory_limit=512M
post_max_size=128M
upload_max_filesize=128M
;<=== End of PHP Selector Custom Options =====

