;---dom---
extension=dom.so


;---fileinfo---
extension=fileinfo.so


;---gd---
extension=gd.so


;---gmp---
extension=gmp.so


;---imagick---
extension=imagick.so


;---imap---
extension=imap.so


;---intl---
extension=intl.so


;---mbstring---
extension=mbstring.so


;---pdo---
extension=pdo.so


;---mysqlnd---
extension=mysqlnd.so


;---mysqli---
extension=mysqli.so


;---pdo_mysql---
extension=pdo_mysql.so


;---pdo_sqlite---
extension=pdo_sqlite.so


;---phar---
extension=phar.so


;---posix---
extension=posix.so


;---sockets---
extension=sockets.so


;---sysvmsg---
extension=sysvmsg.so


;---sysvsem---
extension=sysvsem.so


;---sysvshm---
extension=sysvshm.so


;---xmlreader---
extension=xmlreader.so


;---xmlwriter---
extension=xmlwriter.so


;---xsl---
extension=xsl.so


;---zip---
extension=zip.so



