;---ioncube_loader---
zend_extension=/opt/alt/php51/usr/lib64/php/modules/ioncube_loader.so

;---dom---
extension=dom.so

;---gd---
extension=gd.so

;---imap---
extension=imap.so

;---mbstring---
extension=mbstring.so

;---mysql---
extension=mysql.so

;---mysqli---
extension=mysqli.so

;---pdo---
extension=pdo.so

;---pdo_mysql---
extension=pdo_mysql.so

;---pdo_sqlite---
extension=pdo_sqlite.so

;---sockets---
extension=sockets.so

;---sysvmsg---
extension=sysvmsg.so

;---sysvsem---
extension=sysvsem.so

;---sysvshm---
extension=sysvshm.so

;---xmlreader---
extension=xmlreader.so

;---xmlwriter---
extension=xmlwriter.so

;---xsl---
extension=xsl.so

